name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
          npm-version: 9.5.1
      - name: Install dependencies
        run: npm ci
      - run: npm test